title: ""
draw_x: false
xaxis: |
  $\mathcal{E}/\mathcal{E}_{F}$
yaxis: |
  $E_{self}(k(\mathcal{E}))/\mathcal{E}_{F}$
legend: true
fock:
  style: "--"
  label: |
    rovnica (137)
  color: "black"
1ef:
  label: |
    $\frac{\hbar}{2\tau}=\mathcal{E}_F$
0.1ef:
  label: |
    $\frac{\hbar}{2\tau}=10^{-1}\mathcal{E}_F$
0.01ef:
  label: |
    $\frac{\hbar}{2\tau}=10^{-2}\mathcal{E}_F$
0.001ef:
  label: |
    $\frac{\hbar}{2\tau}=10^{-3}\mathcal{E}_F$